package lk.ijse.encoreDecore.util;

public enum Routes {
     LOGIN, FORGET,
     AVAILABILITY, SERVICE, ORDER, PAYMENT_DETAILS,
     ANNIVERSARY, BABY_SHOWER, BATCH_REUNION, BIRTHDAY, CUSTOM_PARTY,WEDDING,
     ANNIVERSARY_SERVICE_DETAILS,BABY_SHOWER_SERVICE_DETAILS,BATCH_REUNION_SERVICE_DETAILS,BIRTHDAY_SERVICE_DETAILS,CUSTOM_PARTY_SERVICE_DETAILS,WEDDING_SERVICE_DETAILS,

     CUSTOMER, WEDDING_PLACE_ORDER,ANNIVERSARY_PLACE_ORDER,BABY_SHOWER_PLACE_ORDER,BATCH_REUNION_PLACE_ORDER,BIRTHDAY_PLACE_ORDER,CUSTOM_PLACE_ORDER, MAKE_PAYMENT,
     DASHBOARD, EMPLOYEE, PACKAGE, SALARY, PAYMENTS, ACCOUNT
}
